### ISSUE TITLE
Si la clef n'est pas bonne ?

### ISSUE THREAD

**Issue by Grandnainconnu** [Omen-/dofus-key-finder#2]
Bonjour,

J'aimerais savoir si il y a un moyen de régénérer une approche pour une certaine map?
La carte 1716 (31, 7 - Jungle profonde du Moon) ne fonctionne pas après 2 algos testés...

Image de la carte:
http://prntscr.com/h19vvl

Merci d'avance !
Cordialement.

**Comment by ydainna** [comment]
salut.
se n'est pas la seul map qui bug ^^ des maps de l'ilot et stitch bug aussi idem aprés avoir test les deux algo c'est exactement le même probléme

**Comment by Grandnainconnu** [comment]
Ah moi l'ilot estich fonctionne :/

**Comment by arbll** [comment]
Toutes les maps qui ont une clef dont la longueur modulo 10 est égale a 0 sont très difficiles a récupérer. Un truk que vous pouvez tester avec mon algo : faite un bdd contenant que les maps de la zone que vous cherchez a décrypter, y'a moyen que ça améliore les choses

**Comment by ydainna** [comment]
> Ah moi l'ilot estich fonctionne :/

bizzard chez moi les maps 12154, 12164 et 12166 bug en faite y a des élément de decord en trop (sur la 12154) et des élément qui manque sur les 12164 et 12166

**Comment by Grandnainconnu** [comment]
Pour la 12164 et 12166 j'ai pareil que sur http://mapkeys.ancestra.io/gallery.html?id=12164_0903181140 et http://mapkeys.ancestra.io/gallery.html?id=12166_0901271756

Pour la 12154 en effet y'a une grosse pierre au milieu mais je pense que c'est fait expres...

**Comment by arbll** [comment]
Si vous avez de meilleurs résultats avec l'algo de Smarken sur certaines map je veux bien les ids pour regarder

**Comment by Grandnainconnu** [comment]
Bah du coup 12164 et 12166

**Comment by arbll** [comment]
Tu peux me passer la clef que t'as pour ces deux maps ? Avec la date aussi si possible.

**Comment by Grandnainconnu** [comment]
12164:
Date: 0903181140
Key: 4D46753D42755B40652C3E5643536B432E54372C40463F6C5268363F79505E56577846394163472E2A516A7D5E2C467A362C3C7D66387C253262382F607C35675568253235472931734063452C29642D2034213F606A677E2479735471673B2D234B6C25326279444B78204C6B7559404F7F777022737F5A39335A22353C7C7C48276B7D62477E21512532353334553B673471686D212670596A4B7C25326264323E782C6A513972635A41216658625758445058235F467B696D5B6E3259387D5F4825326247212F23474872392C544B49385B4D3C486F702475377F5A583557482A7A304C60413E63717F627F34304F71265A7343

12166:
Date: 0901271756
Key: 263E6B204C7B253235472D2C3A654D544E22303B377129694F5C3147356C5E3865634F386D643D796F76396F465D6C5D353E2A604A2D7B54704361474A376E28612C6E75773350312E5D73314E4838766D396546495C3E506D364A7F444B3E503C3066725049366B512F692F3D2420597C46283F697845526560465637366D4F5C782D3872407B764C653F726C3E4D704848276B36557F7D773471493627762E3C6838715D32484542505B40323F29

**Comment by ydainna** [comment]
4d46753d42755b40652c3e5643536b432e54372c40463f6c5268363f79505e56577846394163472e2a516a7d5e2c467a362c3c7d66387c253242382f607c35675568253235472931734063452c29642d2034213f606a677e2479735471673b2d234b6c25324279444b78204c6b7559404f7f777022737f5a39335a22353c7c7c48276b7d62477e21512532353334553b673471686d212670596a4b7c25324264323e782c6a513972635a41216658625758445058235f467b696d5b6e3259387d5f4825324247212f23474872392c544b49385b4d3c486f702475377f5a583557482a7a304c60413e63717f627f34304f71265a7343

pourtent je ressort la même key que toi avec cette algo la et smarken

edit : elle fonctionne en faite ... je sais d'ou viens le bug c'est l'editeur de map qui doit mal lire la key ...

**Comment by arbll** [comment]
Non y'a une petite diff sur 6 qui devient un 4. Je sais pourquoi ça fait ça mais en gros si je corrige ce "bug" (c'est pas vraiment un bug, plus un paris qu'on prend dans nos algo) d'autres maps qui n'avais pas de défaut vont avoir des défauts.

Il y a quand même un moyen de "corriger" ça : si vous identifiez une map qui marche mieux sur l'algo de Smarken, ajoutez la clef et le decryptedData a la BDD de mon algo. Ça amélioreras le pourcentage de réussite

**Comment by ydainna** [comment]
je viens de test la map 12164 et ig elle bug pas mais sur l'editeur de map si

**Comment by arbll** [comment]
@Hetarnam Tu peux tester ça pour ta première map ? 502a672832786368334f7d6a50586f6e72643f7e34756c4335524143534a78752051447d2f7b6f2532354d553c443525323576724b392e77502f4f384553313a284f3458573d276c2265383142694e236f68585f3c6423535c6f3e7e4d733e6e6e344e556e64223d403149604036364c31686e46643a406723696831533f31725b7634733b6f316a482665775164662269417e4f58235d3e2f3c6d2d452120205d3b65744e213f32506d30385155232532422c387e674c4a763c

Edit: https://imgur.com/a/GQqWc  :p

**Comment by arbll** [comment]
@Hetarnam @ydainna https://github.com/Omen-/dofus-key-finder/releases/tag/v0.5

* Sauvegarde en BDD de la clef et du decryptedData
* Vous pouvez filtrer les données utilisées dans les stats par subAreaId. En gros vous mettez le même subAreaId que la map que vous avez du mal a casser et y'as des chances que sa améliore le résultat

**Comment by ydainna** [comment]
m'okey merci je vais test ça

**Comment by ydainna** [comment]
du coup la new cmd c'est quoi ?

**Comment by arbll** [comment]
J'ai update le readme mais tu peux toujours faire `findmapkey.exe -h`

**Comment by ydainna** [comment]
ok d'accord part contre y a pas moyens de crée une cmd qui casse les keys en masses ? genre pas besoin de mettre d'id de map dans la cmd : findmapkey.exe -db="root:@/maps" -maps=12154,12155
maps juste : findmapkey.exe -db="root:@/maps" -maps (ou unt ruc du genre)
se qui permetrais de casser toutes les keys map présente dans une table et save lamapdata decrypt ?

**Comment by arbll** [comment]
Tu peux faire ça a la main avec une requête SQL et quelques rechercher/replacer

```
SELECT DISTINCT id FROM `static_maps` WHERE  `key` IS NULL
```
Liste de toutes les maps avec des clef inconnues:
[unknown_key.txt](https://github.com/Omen-/dofus-key-finder/files/1411184/unknown_key.txt)

**Comment by ydainna** [comment]
ok merci part contre quand j'use la fonction du subarea ça bug (maps id 12154)
panic: runtime error: integer divide by zero

goroutine 1 [running]:
github.com/omen-/dofus-key-finder/dfkey.eliminateImpossibleValuesInDecryptedData(0xc04888b500, 0x12b6, 0x1500, 0x0, 0xc049a8c000, 0x12b6, 0x12b6, 0xc0420be0f0, 0xa, 0xa, ...)
        C:/Users/Arthur/Desktop/projects/Go/src/github.com/omen-/dofus-key-finder/dfkey/key.go:79 +0x229
github.com/omen-/dofus-key-finder/dfkey.findPossibleDecryptedDataAndKeyLength(0xc04888b500, 0x12b6, 0x1500, 0xc042098500, 0xc, 0x10, 0x0, 0x1, 0x5, 0xa)
        C:/Users/Arthur/Desktop/projects/Go/src/github.com/omen-/dofus-key-finder/dfkey/key.go:62 +0x13f
github.com/omen-/dofus-key-finder/dfkey.GuessKey(0x2f7a, 0xc0439b6000, 0x256c, 0x0, 0x0, 0x0, 0x0, 0xc0424057c0, 0xa, 0x1f5, ...)
        C:/Users/Arthur/Desktop/projects/Go/src/github.com/omen-/dofus-key-finder/dfkey/key.go:11 +0xb2
main.main()
        C:/Users/Arthur/Desktop/projects/Go/src/github.com/omen-/dofus-key-finder/cmd/findmapkey/main.go:42 +0x331

**Comment by arbll** [comment]
Oui je vois, c'est pas vraiment un bug, c'est juste que t'as 0 ou pas assez de map décrypté en base pour l'ilot et que du coup il a pas assez de données.

Je vais essayer d'ajouter un message plus explicite, essaye de décrypter tout l'ilot en mode normal et relance ta commande ensuite

**Comment by ydainna** [comment]
c'est bon ça fonctionne aprés avoir decrypt tout

**Comment by arbll** [comment]
En gros si vous voulez tout casser : 
1. Lancez en mode normal sur toutes les map inconnues
2. Des que vous trouvez un bug en jeu utilisez -subareas pour essayez de le corriger

**Comment by ydainna** [comment]
yep je viens de corriger la map 12154 qui ne bug désormais plus avec le subareas du coup la key est désormais bonne

**Comment by Grandnainconnu** [comment]
@Omen- en effet c'est mieux!

Tu pourrais faire un filtre qui applique sur toutes les maps de la db?

En soit ma DB est full, et environ 90% des keys sont bonnes, mais certaines non, donc j'aimerais corriger tout ça, sur toutes les maps buggés

EDIT: je trouve pas le même resultat pour la clef de la map 1713 avec le -subareas
EDIT 2: essaye avec la map 433, perso j'ai ça: http://prntscr.com/h1gimw

**Comment by arbll** [comment]
Pas bien compris désolé, mais je pense que ce que tu veux faire est pas possible. Je peux pas détecter les map buggés du coup il y auras forcement du travail à la main. J'ai pas vraiment amélioré l'algo, c'est plus une autre manière de faire qui a des chances de marcher si la première approche passe pas. En gros comme j'ai dis plus haut la stratégie c'est : 

> 1. Lancez en mode normal sur toutes les map inconnues
> 2. Des que vous trouvez un bug en jeu utilisez -subareas pour essayez de le corriger

**Comment by Grandnainconnu** [comment]
> @Hetarnam Tu peux tester ça pour ta première map ? 502a672832786368334f7d6a50586f6e72643f7e34756c4335524143534a78752051447d2f7b6f2532354d553c443525323576724b392e77502f4f384553313a284f3458573d276c2265383142694e236f68585f3c6423535c6f3e7e4d733e6e6e344e556e64223d403149604036364c31686e46643a406723696831533f31725b7634733b6f316a482665775164662269417e4f58235d3e2f3c6d2d452120205d3b65744e213f32506d30385155232532422c387e674c4a763c
Edit: https://imgur.com/a/GQqWc :p

Comment t'as trouvé ça?

**Comment by arbll** [comment]
Je vois d’où ça viens et c'est relou :/. En gros faut avoir au maximum possible la BDD remplie de map vérifiées sinon les mauvaises maps "infectent" les autres. Reprend une BDD clean pour travailler sur ce genre de maps pour l'instant.

Je pense que je vais modifier le code pour avoir une BDD input et une BDD output du coup

**Comment by Grandnainconnu** [comment]
Ma DB est pleine mais il doit y avoir trop de maps buggées...

**Comment by arbll** [comment]
https://github.com/Omen-/dofus-key-finder/releases/tag/v0.6

Les maps sont output dans une table a part pour pas empoisonner les données si elle sont buggés

@Hetarnam T'as testé avec une base clean ?

**Comment by ydainna** [comment]
Moi je serais curieu de s'avoir pour le XOR vulnerable etc ^^

**Comment by arbll** [comment]
Tu veux dire pour une explication ? Normalement j’écris un article demain. Ça seras en anglais par contre

**Comment by Grandnainconnu** [comment]
@Omen- je vais test ça dans la journée avec une base clean, je vais dégagé les clefs qui sont pas à 100% valides

**Comment by ydainna** [comment]
salut j'ai une erreur en voulant faire la map : 12099
panic: Could not find keyLength. This probably means you do not have enough decryptedData. Try without -subarea or add more decryptedData in the selected subarea.

goroutine 1 [running]:
github.com/omen-/dofus-key-finder/dfkey.findPossibleDecryptedDataAndKeyLength(0xc04206d500, 0x12b6, 0x1500, 0xc042080a00, 0xd, 0x10, 0x0, 0x1, 0x5, 0xa)
        C:/Users/Arthur/Desktop/projects/Go/src/github.com/omen-/dofus-key-finder/dfkey/key.go:61 +0x1f1
github.com/omen-/dofus-key-finder/dfkey.GuessKey(0x2f43, 0xc0420ca000, 0x256c, 0x0, 0x0, 0x0, 0x0, 0xc0420082b6, 0xa, 0x16, ...)
        C:/Users/Arthur/Desktop/projects/Go/src/github.com/omen-/dofus-key-finder/dfkey/key.go:11 +0xb2
main.main()
        C:/Users/Arthur/Desktop/projects/Go/src/github.com/omen-/dofus-key-finder/cmd/findmapkey/main.go:42 +0x331


j'ai essayer de add : -subareas=22 a la fin mais idem .. une erreur .. alors qu'avec d'autres maps ça fonctionne

**Comment by arbll** [comment]
Ajoute un maximum de maps que tu a **vérifiées** dans cette subarea à `static_maps`. Si t'as déjà fait le maximum de ce côté ajoute des subarea qui ressemblent à celle de ta map. ex : champs d'astrub/champ d'ankama

**Comment by ydainna** [comment]
(je suis chiant) mais est-ce qu'il faut toutes les mapdata crypt dans la db pour decrypt une map ? car j'ai cette erreur la quand je veux decrypt une map (j'ai pas toutes les mapdata crypt) y a que celle que je veux decrypt qu'il y a (mapdata)
https://imgur.com/a/lNsC3

**Comment by arbll** [comment]
Oui il s'attend a avoir tout les champs remplis sauf key/decryptedData/sa

**Comment by ydainna** [comment]
a merde ok merci ./....
car j'ai perdu ma table ou j'avais trier toutes les maps en double et garder que celles a jour du client .. et j'ai aucun script pour refaire ça j'avais fais ça a la main ... du coup j'ai plus aucune mapdata crypt ...

**Comment by ydainna** [comment]
personne n'a la table a jour avec les map a jour dedans sens les doublons svp ? :/

**Comment by arbll** [comment]
@ydainna Si tu veux essayer de comprendre comment l'algo [fonctionne](http://arthur.bell.al/blog/breaking-dofus-1.29.1-maps-encryption/). Attention c'est un peu technique.

Je close, ouvrez une nouvelle issue si vous avez d'autres problèmes.
