### ISSUE TITLE
j'ai un soucis il me sort des 000000 pour les clé 

### ISSUE THREAD

**Issue by MrChaotik** [Omen-/dofus-key-finder#3]
bonjour, 

jai un souci il me sort que des 0 pour les key 

![image](https://user-images.githubusercontent.com/18539325/31960194-43eb2df0-b8f7-11e7-9fd6-14e6488fd9a2.png)

![image](https://user-images.githubusercontent.com/18539325/31960231-6707bb00-b8f7-11e7-82f0-ad85164c9803.png)

alors que  ydaina lui sa fonctionne

**Comment by arbll** [comment]
Cette map fonctionne chez moi : 
![image](https://user-images.githubusercontent.com/9051073/31961079-fd493d26-b8f9-11e7-9779-ea9470a6a401.png)

Ça viens probablement d'un problème avec ta base. Ta table static_maps est bien installé ?

**Comment by MrChaotik** [comment]
oui jai pris celle de la passerelle

**Comment by arbll** [comment]
Tu peux m’exécuter ça sur ta BDD ? `SELECT COUNT(*) FROM static_maps` et me donner le resultat

**Comment by MrChaotik** [comment]
![image](https://user-images.githubusercontent.com/18539325/31962191-289793f8-b8fd-11e7-9dec-5aa52a5ffecd.png)
jai réinstaler la bdd sa donne sa 
![image](https://user-images.githubusercontent.com/18539325/31962233-517039d8-b8fd-11e7-95f1-74b1947217cf.png)

**Comment by arbll** [comment]
C'est normal, -subarea a besoin d'avoir des maps déjà décryptées dans la même subarea pour fonctionner.
Suis les indications ici : [Workflow to decrypt map X](https://github.com/Omen-/dofus-key-finder/blob/master/README.md#workflow-to-decrypt-map-x)

**Comment by MrChaotik** [comment]
a oui exacte excuse moi  de t’avoir déranger  merci :)

**Comment by arbll** [comment]
T’inquiète, pense a me mettre une étoile si tu veux me remercier pour le travail ;)

**Comment by MrChaotik** [comment]
voilas c fait :)

**Comment by MrChaotik** [comment]
dit moi j'ai une basse de donner avec déjàs les map  et key il me manque juste les map décrypter pourais tu m'aider pour sa ?

**Comment by arbll** [comment]
Y'a ça si tu veux https://github.com/Manghao/DofusMapDataDecypher

**Comment by MrChaotik** [comment]
Oui c'est celui que j'utilise mes il est un peu chiant de devoir tout faire à la main. Car je doit ouvrir le swf pour récupérer la map crypté et de lancer éclipse à chaque fois mes t'embête pas ou pire je continue comme ça
